### ISSUE TITLE
OOM errors with Bonito model calls

### ISSUE THREAD

**Issue by bernard-kim** [fenderglass/ABruijn#336]
Hi Mikhail,

I'm seeing a curious increase in out of memory errors at the stage where Flye is "Generating sequence" for the disjointings. I get OOM errors sometimes with ultra-long datasets (however not typically at this stage, I think?), but in the past I've been able to deal with this by dropping the number of threads. Recently I've been re-basecalling data with the new Guppy 4.4.0+Bonito models and now assemblies using parameter values that worked fine before are throwing OOM errors.

Here's what the runs looks like before they go OOM on my machine with 256GB RAM.

```
flye --threads 40 --genome-size 140m --nano-raw D.melanogaster.bonito.passReads.fastq --out-dir D.melanogaster.FlyeAssembly
[2021-01-08 00:26:21] INFO: Starting Flye 2.8.2-b1691
[2021-01-08 00:26:21] INFO: >>>STAGE: configure
[2021-01-08 00:26:21] INFO: Configuring run
[2021-01-08 00:26:55] INFO: Total read length: 8981503406
[2021-01-08 00:26:55] INFO: Input genome size: 140000000
[2021-01-08 00:26:55] INFO: Estimated coverage: 64
[2021-01-08 00:26:55] INFO: Reads N50/N90: 20603 / 5772
[2021-01-08 00:26:55] INFO: Minimum overlap set to 5000
[2021-01-08 00:26:55] INFO: >>>STAGE: assembly
[2021-01-08 00:26:55] INFO: Assembling disjointigs
[2021-01-08 00:26:55] INFO: Reading sequences
[2021-01-08 00:27:22] INFO: Counting k-mers:
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2021-01-08 00:32:53] INFO: Filling index table (1/2)
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2021-01-08 00:35:55] INFO: Filling index table (2/2)
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2021-01-08 00:39:47] INFO: Extending reads
[2021-01-08 00:44:23] INFO: Overlap-based coverage: 51
[2021-01-08 00:44:23] INFO: Median overlap divergence: 0.0805464
0% 10% 20% 30% 40% 60% 70% 80% 90% 100%
[2021-01-08 01:44:42] INFO: Assembled 127 disjointigs
[2021-01-08 01:44:47] INFO: Generating sequence
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% [2021-01-08 01:45:34] ERROR: Looks like the system ran out of memory
[2021-01-08 01:45:34] ERROR: Command '['flye-modules', 'assemble', '--reads', 'D.melanogaster.bonito.passReads.fastq', '--out-asm', '/media/bernardkim/working/D.melanogaster/D.melanogaster.FlyeAssembly/00-assembly/draft_assembly.fasta', '--config', '/home/bernardkim/miniconda3/lib/python3.7/site-packages/flye/config/bin_cfg/asm_raw_reads.cfg', '--log', '/media/bernardkim/working/D.melanogaster/D.melanogaster.FlyeAssembly/flye.log', '--threads', '40', '--genome-size', '140000000', '--min-ovlp', '5000']' died with <Signals.SIGKILL: 9>.
[2021-01-08 01:45:34] ERROR: Pipeline aborted
```

Any idea what could be going on?

**Comment by mikolmogorov** [comment]
Hi,

Very strange! I previously had never seen Flye using excessive memory on that stage - it only does pairwise alignments between reads to generate disjointigs at this point. 256Gb of RAM should be more than enough.

I think it could be a bug in the alignment code that results into an incorrect memory allocation. Could you please provide the full log? Is the error reproducible from run to run? Since I have never seen this happening before, I might need the original data to reproduce the problem on my machine.

Mikhail

**Comment by bernard-kim** [comment]
Hi Mikhail,

The error is completely reproducible across runs: I tried with ```--threads``` 80, 70, 60, and 40 and got the same error across them. When I used ```--threads 10``` the assembly completed successfully.

I don't have the full log but can re-run it in several days (backlogged with other jobs). Here are the reads. Maybe they are more useful for you anyway?

https://stanford.box.com/s/6i20x07yqm4ygc3ptt10eooozxtrbv4q

p.s. please feel free to share/distribute however you wish. Guppy 3.2.4 basecalls of the same data should be available on NCBI.

**edit**: By the way, we have the same issues with Plasmodium falciparum genome assemblies (~23 Mb). In some cases lots of ultra-long reads and bonito basecalls. I can't share those data publicly but would be happy to share privately if you're interested in taking a look.

**Comment by bernard-kim** [comment]
Thought I deleted the log but turns out I didn't. Here's the full log of the failed (and finally successful) runs.

[flye.log](https://github.com/fenderglass/Flye/files/5816713/flye.log)

**Comment by mikolmogorov** [comment]
@bernard-kim thank you for sharing the data! I will take a look - likely it is a bug somewhere in the code rather than a memory issue..

**Comment by mikolmogorov** [comment]
@bernard-kim 

Looks like there was indeed an issue with high memory usage, which only shows up for ultra-long reads. E.g. the final stage of disjointig sequence generation consumed 200Gb+, while usually it is just a few Gb.

I think I have now fixed this issue, and the new code is currently in the `flye-devel` branch. It now consumes ~50Gb RAM at peak, which should remain relatively flat for larger genomes as well (wrt to the final stage). Feel free to give it a try - curious if it will help with your Plasmodium genome. I was using 30 threads in my tests.

Once I will have a chance to do more testing on my side, I will integrate the code into the next release..

**Comment by bernard-kim** [comment]
@fenderglass 

Tried out the new version and the problem seems to have mostly disappeared. Thanks!

I'm still having issues with one run in particular, about 90X coverage of decently long stuff (read N50 ~40kb). It doesn't have _that_ much data in >100kb reads either, about 300Mb while other runs have 300-1000Mb in >100kb stuff. Here's the log output:

```
[2021-01-21 09:13:01] INFO: Starting Flye 2.8.2-b1693
[2021-01-21 09:13:01] INFO: Resuming previous run
[2021-01-21 09:13:01] INFO: >>>STAGE: assembly
[2021-01-21 09:13:01] INFO: Assembling disjointigs
[2021-01-21 09:13:01] INFO: Reading sequences
[2021-01-21 09:13:30] INFO: Counting k-mers:
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2021-01-21 09:15:04] INFO: Filling index table (1/2)
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2021-01-21 09:16:19] INFO: Filling index table (2/2)
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2021-01-21 09:23:47] INFO: Extending reads
[2021-01-21 10:05:56] INFO: Overlap-based coverage: 86
[2021-01-21 10:05:56] INFO: Median overlap divergence: 0.103091
0% 10% 20% 30% 40% 50% 70% 80% 90% 100%
[2021-01-21 10:59:08] INFO: Assembled 18 disjointigs
[2021-01-21 10:59:09] INFO: Generating sequence
0% [2021-01-21 10:59:09] ERROR: Caught unhandled exception: std::bad_alloc
[2021-01-21 10:59:09] ERROR:    flye-modules(_Z16exceptionHandlerv+0xd0) [0x44bff0]
[2021-01-21 10:59:09] ERROR:    /lib64/libstdc++.so.6(+0x5e746) [0x7f88e2b2d746]
[2021-01-21 10:59:09] ERROR:    /lib64/libstdc++.so.6(+0x5e773) [0x7f88e2b2d773]
[2021-01-21 10:59:09] ERROR:    /lib64/libstdc++.so.6(+0xb5105) [0x7f88e2b84105]
[2021-01-21 10:59:09] ERROR:    /lib64/libpthread.so.0(+0x7dd5) [0x7f88e23a2dd5]
[2021-01-21 10:59:09] ERROR:    /lib64/libc.so.6(clone+0x6d) [0x7f88e20cc02d]
[2021-01-21 10:59:10] ERROR: Command '['flye-modules', 'assemble', '--reads', 'pfal_MA26.bonito.passReads.fastq.gz', '--out-asm', '/scratch/users/bkim331/pfal/pfal_MA26.FlyeAssembly/00-assembly/draft_assembly.fasta', '--config', '/home/groups/dpetrov/bernard/tools/Flye/flye/config/bin_cfg/asm_raw_reads.cfg', '--log', '/scratch/users/bkim331/pfal/pfal_MA26.FlyeAssembly/flye.log', '--threads', '16', '--genome-size', '23000000', '--min-ovlp', '5000']' died with <Signals.SIGABRT: 6>.
[2021-01-21 10:59:10] ERROR: Pipeline aborted
memusg: vmpeak: 20171812 kb
```
Full log:
[flye.log](https://github.com/fenderglass/Flye/files/5851831/flye.log)

It seems like a memory issue but there seems to be plenty of RAM relative to the memory used by Flye (see memusg output of peak ~20GB). I also tried turning down the `--asm-coverage` but same error.

I could share the problematic data with you through email or something if it would be helpful for you. Can't share them publicly yet unfortunately.

**Comment by mikolmogorov** [comment]
@bernard-kim thank you! Yes, if you could send the problematic dataset to fenderglass@gmail.com - that would help a lot.

**Comment by mikolmogorov** [comment]
@bernard-kim thanks for sending the data. Looks like I have missed a corned case in my last update. I've added a fix to `flye-devel` - it should work for you now! Let me know if you have any other issues.

**Comment by bernard-kim** [comment]
@fenderglass It looks like everything is working. Not seeing any more out of memory issues for any of the ultra-long Plasmodium or Drosophila datasets I've tested this with. 

Will let you know if anything else pops up. Closing the issue until then.

Thanks again for addressing this so quickly!
